-- 0012: Seed Warunki 39 penalty rules

insert into penalty_rules (warunki_point, title, description, penalty_amount_eur, penalty_formula, trigger_type, is_auto, extra_config) values
(1,  'Warunki — інтегральна частина',      'Warunki є інтегральною частиною замовлення',                             null,   null,                          'text',    false, '{}'),
(2,  'Netto «all in»',                      'Фрахт нетто включає всі витрати',                                         null,   null,                          'text',    false, '{}'),
(3,  'Цесія заборонена',                     'Цесія заборонена без письмової згоди',                                    null,   null,                          'text',    false, '{}'),
(4,  'Зміни лише письмово',                  'Будь-які зміни лише письмово',                                            null,   null,                          'text',    false, '{}'),
(5,  'Штрафи кумулюються',                   'Штрафи складаються між собою',                                            null,   null,                          'text',    false, '{}'),
(6,  'Суд',                                  'Суд за місцем Zleceniodawcy',                                             null,   null,                          'text',    false, '{}'),
(7,  'Право заліку',                         'Zleceniodawca має право заліку',                                          null,   null,                          'text',    false, '{}'),
(8,  'Kodeks Cywilny + CMR',                 'Правова основа: KC + Конвенція CMR',                                      null,   null,                          'text',    false, '{}'),
(9,  'Auto-accept 30 хв',                    'Відсутність заперечень 30 хв = прийняття',                                null,   null,                          'timer',   true,  '{"minutes": 30}'),
(10, 'Стан транспорту',                      'Техн.-санітарний стан на вимогу',                                         null,   'cost_of_replacement',         'manual',  false, '{}'),
(11, 'ЗІЗ водія',                            'Черевики зі сталевими носками, жилет, окуляри, каска, рукавиці',          100,    null,                          'manual',  false, '{}'),
(12, 'ADR без сертифіката',                  'ADR-пакет + права обов''язкові при adr=true',                              100,    null,                          'status',  true,  '{"check":"driver.has_adr_cert"}'),
(13, 'Без термографа 14 днів',               'Термограф не надіслано за 14д від розвантаження',                         150,    '150 + 10 admin',              'cron',    true,  '{"days":14,"admin_eur":10}'),
(14, 'Неподання під завантаження',            'Неподання = 100% фрахту + пошук заміни',                                  null,   '100% of freight',             'status',  true,  '{}'),
(15, 'Перевірка ящиків',                     'Обов''язок перевірити відповідність',                                     null,   null,                          'manual',  false, '{}'),
(16, 'Простій 24h',                          'До 24 год — безкоштовно',                                                 null,   null,                          'manual',  false, '{}'),
(17, 'Паркування охоронюване',               'Паркування лише на охоронюваних майданчиках',                             null,   'rażące niedbalstwo',          'manual',  false, '{}'),
(18, 'Доп.завантаження без згоди',            'Додаткове завантаження без згоди',                                        1000,   null,                          'manual',  false, '{}'),
(19, 'Неправдива інформація',                'Неправдива інформація про хід перевезення',                                150,    null,                          'manual',  false, '{}'),
(20, 'Не повідомив про проблему',             'Не повідомив диспетчера про проблему',                                    150,    null,                          'manual',  false, '{}'),
(21, 'Перевірка вантажу',                    'Обов''язок перевірити вантаж при завантаженні',                           null,   null,                          'manual',  false, '{}'),
(22, 'Запізнення на розвантаження',          '100 EUR/год до суми фрахту',                                              100,    '100 * hours_late',            'cron',    true,  '{"per_hour_eur":100}'),
(23, 'CMR + WZ правила',                     'Оформлення документів',                                                   null,   null,                          'manual',  false, '{}'),
(24, 'Оплата після реклам. процедури',        'Оплата після завершення реклам. процедури',                                null,   null,                          'manual',  false, '{}'),
(25, 'Передача субпідряднику',                'Передача без згоди = 10 000 EUR',                                         10000,  null,                          'manual',  false, '{}'),
(26, 'Відміна до 12 год',                    'Відміна до 12 год перед завантаженням — безкоштовно',                     null,   null,                          'timer',   true,  '{}'),
(27, 'Делегування',                          'Недотримання правил делегування',                                         null,   'істотне порушення',           'manual',  false, '{}'),
(28, 'Сплата штрафу 15 днів',                'Термін сплати нарахованого штрафу',                                       null,   null,                          'manual',  false, '{"days":15}'),
(29, 'Обхід клієнтів 5 років',                'Заборона прямої співпраці з клієнтами BAKSPEED 5 років',                   100000, null,                          'text',    false, '{"years":5}'),
(30, 'OC/OCP обов''язкові',                  'OC ≥500k EUR, OCP = вартість вантажу',                                    null,   null,                          'manual',  true,  '{"min_oc_eur":500000}'),
(31, 'Перевірка палет',                      'Перевірка стану палет при завантаженні',                                  null,   null,                          'manual',  false, '{}'),
(32, 'Паліти 21 день',                       'EPAL 20, Düsseldorfer 15, H1 100, Gitterbox 100',                         null,   'per pallet',                  'cron',    true,  '{"EPAL":20,"DUSSELDORFER":15,"H1":100,"GITTERBOX":100,"days":21}'),
(33, 'Підтвердження невиконання обміну',      null,                                                                      null,   null,                          'manual',  false, '{}'),
(34, 'Нота за паліти',                       null,                                                                      null,   null,                          'manual',  false, '{}'),
(35, 'Документи >14 днів',                   'Пізні оригінали: +30 днів payment АБО -20% netto',                        null,   '60->90 days OR -20% netto',   'cron',    true,  '{"days":14,"choices":["term_extended","pct_reduction"],"pct":20,"extra_days":30}'),
(36, 'CMR з іншими даними',                  'Вимагає письмової згоди',                                                 null,   null,                          'manual',  false, '{}'),
(37, 'Реквізити на фактурі',                  'Обов''язкові реквізити: BAKSPEED Sp. z o.o. + NIP + адреса',              null,   null,                          'text',    false, '{}'),
(38, 'Standard term 60 днів',                'Дефолтний термін оплати перевізнику',                                     null,   null,                          'manual',  true,  '{"days":60}'),
(39, 'VAT Whitelist',                        'Перевірка Білої Листи перед платежем',                                    null,   null,                          'status',  true,  '{}');
